-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  phone text,
  avatar_url text,
  is_artist boolean NOT NULL DEFAULT false,
  is_partner boolean NOT NULL DEFAULT false,
  is_admin boolean NOT NULL DEFAULT false,
  account_type text DEFAULT 'customer'::text CHECK (account_type = ANY (ARRAY['customer'::text, 'artist'::text, 'business_partner'::text])),
  artist_category text CHECK (artist_category = ANY (ARRAY['hair'::text, 'nails'::text, 'makeup'::text, 'lashes'::text])),
  account_status text NOT NULL DEFAULT 'active'::text CHECK (account_status = ANY (ARRAY['active'::text, 'pending_review'::text, 'suspended'::text, 'deleted'::text])),
  suspension_reason text,
  suspended_at timestamp with time zone,
  suspended_by uuid,
  referral_code text UNIQUE,
  referred_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_suspended_by_fkey FOREIGN KEY (suspended_by) REFERENCES auth.users(id),
  CONSTRAINT profiles_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.artists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  display_name text NOT NULL,
  bio text,
  category text NOT NULL CHECK (category = ANY (ARRAY['hair'::text, 'nails'::text, 'makeup'::text, 'lashes'::text])),
  location text,
  suburb text,
  city text,
  latitude numeric,
  longitude numeric,
  avatar_url text,
  cover_url text,
  rating numeric NOT NULL DEFAULT 0,
  review_count integer NOT NULL DEFAULT 0,
  is_verified boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  point_of_contact_name text,
  point_of_contact_phone text,
  moderation_status text NOT NULL DEFAULT 'approved'::text CHECK (moderation_status = ANY (ARRAY['draft'::text, 'scanning'::text, 'approved'::text, 'needs_review'::text, 'rejected'::text])),
  moderation_score numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT artists_pkey PRIMARY KEY (id),
  CONSTRAINT artists_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  artist_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price integer NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 60,
  category text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id)
);
CREATE TABLE public.availability (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  artist_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  CONSTRAINT availability_pkey PRIMARY KEY (id),
  CONSTRAINT availability_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id)
);
CREATE TABLE public.portfolio_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  artist_id uuid NOT NULL,
  image_url text NOT NULL,
  caption text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portfolio_images_pkey PRIMARY KEY (id),
  CONSTRAINT portfolio_images_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  artist_id uuid NOT NULL,
  service_id uuid NOT NULL,
  booking_date date NOT NULL,
  booking_time time without time zone NOT NULL,
  meeting_address text,
  status text NOT NULL DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text])),
  total_amount integer NOT NULL,
  payfast_payment_id text,
  notes text,
  client_poc_name text,
  client_poc_phone text,
  artist_poc_name text,
  artist_poc_phone text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  reminder_sent boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  commission_cents integer,
  payout_cents integer,
  payout_credited_at timestamp with time zone,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id),
  CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewed_id uuid NOT NULL,
  artist_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  review_type text NOT NULL CHECK (review_type = ANY (ARRAY['client_to_artist'::text, 'artist_to_client'::text])),
  moderation_status text NOT NULL DEFAULT 'approved'::text CHECK (moderation_status = ANY (ARRAY['draft'::text, 'scanning'::text, 'approved'::text, 'needs_review'::text, 'rejected'::text])),
  moderation_score numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_reviewed_id_fkey FOREIGN KEY (reviewed_id) REFERENCES public.profiles(id),
  CONSTRAINT reviews_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  partner_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price integer NOT NULL,
  image_url text,
  category text CHECK (category = ANY (ARRAY['hair'::text, 'nails'::text, 'makeup'::text, 'lashes'::text, 'skincare'::text, 'tools'::text, 'other'::text])),
  stock_count integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  moderation_status text NOT NULL DEFAULT 'scanning'::text CHECK (moderation_status = ANY (ARRAY['draft'::text, 'scanning'::text, 'approved'::text, 'needs_review'::text, 'rejected'::text])),
  moderation_score numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  weight_g integer,
  length_cm numeric,
  width_cm numeric,
  height_cm numeric,
  product_type text NOT NULL DEFAULT 'simple'::text CHECK (product_type = ANY (ARRAY['simple'::text, 'variable'::text])),
  package text CHECK (package IS NULL OR (package = ANY (ARRAY['starter'::text, 'growth'::text, 'business'::text, 'premium'::text]))),
  listing_status text NOT NULL DEFAULT 'active'::text CHECK (listing_status = ANY (ARRAY['pending_payment'::text, 'active'::text, 'expired'::text, 'cancelled'::text])),
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  payfast_payment_id text,
  listing_package_id uuid,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_listing_package_id_fkey FOREIGN KEY (listing_package_id) REFERENCES public.listing_packages(id),
  CONSTRAINT products_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  total_amount integer NOT NULL,
  status text NOT NULL DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'paid'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text])),
  shipping_address text,
  contact_name text,
  contact_whatsapp text,
  payment_method text DEFAULT 'payfast'::text CHECK (payment_method = ANY (ARRAY['payfast'::text, 'happypay'::text, 'google_pay'::text, 'ozow'::text])),
  payfast_payment_id text,
  gateway_order_id text,
  gateway_webhook_secret text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  discount_cents integer NOT NULL DEFAULT 0,
  coupon_code text,
  coupon_id uuid,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
  CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price integer NOT NULL,
  commission_cents integer,
  payout_cents integer,
  payout_credited_at timestamp with time zone,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.partner_salons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  partner_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  address text,
  suburb text,
  city text,
  latitude numeric,
  longitude numeric,
  phone text,
  email text,
  website text,
  opening_hours jsonb DEFAULT '{}'::jsonb,
  gallery_urls ARRAY DEFAULT '{}'::text[],
  is_active boolean NOT NULL DEFAULT false,
  subscription_until date,
  moderation_status text NOT NULL DEFAULT 'approved'::text CHECK (moderation_status = ANY (ARRAY['draft'::text, 'scanning'::text, 'approved'::text, 'needs_review'::text, 'rejected'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  instagram_username text,
  youtube_url text,
  services ARRAY DEFAULT '{}'::text[],
  photo_credits integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  CONSTRAINT partner_salons_pkey PRIMARY KEY (id),
  CONSTRAINT partner_salons_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.salon_subscription_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid NOT NULL,
  partner_id uuid NOT NULL,
  amount integer NOT NULL DEFAULT 3500,
  payfast_payment_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text])),
  valid_until date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salon_subscription_payments_pkey PRIMARY KEY (id),
  CONSTRAINT salon_subscription_payments_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.partner_salons(id),
  CONSTRAINT salon_subscription_payments_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  partner_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  image_url text,
  link_url text,
  category text CHECK (category = ANY (ARRAY['hair'::text, 'nails'::text, 'makeup'::text, 'lashes'::text, 'general'::text])),
  package text NOT NULL CHECK (package = ANY (ARRAY['starter'::text, 'growth'::text, 'business'::text, 'premium'::text])),
  ads_count integer NOT NULL DEFAULT 1,
  price integer NOT NULL,
  status text NOT NULL DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'active'::text, 'expired'::text, 'cancelled'::text])),
  payfast_payment_id text,
  starts_at timestamp with time zone,
  expires_at timestamp with time zone,
  moderation_status text NOT NULL DEFAULT 'draft'::text CHECK (moderation_status = ANY (ARRAY['draft'::text, 'scanning'::text, 'approved'::text, 'needs_review'::text, 'rejected'::text])),
  moderation_score numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ads_pkey PRIMARY KEY (id),
  CONSTRAINT ads_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  referrer_id uuid NOT NULL,
  referred_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'rewarded'::text])),
  reward_amount integer DEFAULT 1000,
  rewarded_at timestamp with time zone,
  trigger_ad_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id),
  CONSTRAINT referrals_referred_id_fkey FOREIGN KEY (referred_id) REFERENCES public.profiles(id),
  CONSTRAINT referrals_trigger_ad_id_fkey FOREIGN KEY (trigger_ad_id) REFERENCES public.ads(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL UNIQUE,
  available_balance integer NOT NULL DEFAULT 0,
  pending_balance integer NOT NULL DEFAULT 0,
  approved_balance integer NOT NULL DEFAULT 0,
  total_earned integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  wallet_id uuid NOT NULL,
  amount integer NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['credit'::text, 'debit'::text])),
  description text NOT NULL,
  reference_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  clears_at timestamp with time zone,
  source_type text CHECK (source_type = ANY (ARRAY['booking'::text, 'order_item'::text, 'referral'::text, 'withdrawal'::text, 'adjustment'::text])),
  source_id uuid,
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallets(id)
);
CREATE TABLE public.withdrawals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  amount integer NOT NULL,
  bank_name text NOT NULL,
  account_number text NOT NULL,
  account_holder text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'paid'::text, 'rejected'::text])),
  processed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT withdrawals_pkey PRIMARY KEY (id),
  CONSTRAINT withdrawals_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reporter_id uuid NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['ad'::text, 'product'::text, 'salon'::text, 'review'::text, 'artist'::text])),
  content_id uuid NOT NULL,
  reason text NOT NULL CHECK (reason = ANY (ARRAY['spam'::text, 'offensive'::text, 'fraud'::text, 'misleading'::text])),
  description text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'reviewed'::text, 'dismissed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.wishlists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  artist_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wishlists_pkey PRIMARY KEY (id),
  CONSTRAINT wishlists_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT wishlists_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id)
);
CREATE TABLE public.store_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  salon_id uuid NOT NULL,
  client_id uuid,
  client_name text NOT NULL,
  client_phone text NOT NULL,
  service text NOT NULL CHECK (service = ANY (ARRAY['hair'::text, 'nails'::text, 'makeup'::text, 'lashes'::text])),
  booking_date date NOT NULL,
  booking_time time without time zone NOT NULL,
  notes text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT store_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT store_bookings_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.partner_salons(id),
  CONSTRAINT store_bookings_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.users(id)
);
CREATE TABLE public.photo_upload_charges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  salon_id uuid NOT NULL,
  image_url text NOT NULL,
  amount_cents integer NOT NULL DEFAULT 500,
  payfast_id text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT photo_upload_charges_pkey PRIMARY KEY (id),
  CONSTRAINT photo_upload_charges_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id),
  CONSTRAINT photo_upload_charges_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.partner_salons(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  description text,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL,
  scope text NOT NULL DEFAULT 'cart'::text CHECK (scope = ANY (ARRAY['cart'::text, 'product'::text])),
  product_id uuid,
  min_order_cents integer,
  max_uses integer,
  used_count integer NOT NULL DEFAULT 0,
  expires_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT coupons_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.site_config (
  key text NOT NULL,
  value text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT site_config_pkey PRIMARY KEY (key),
  CONSTRAINT site_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_otp (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email text NOT NULL,
  otp_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:10:00'::interval),
  used boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_otp_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_variants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  label text NOT NULL,
  price integer NOT NULL,
  stock_count integer NOT NULL DEFAULT 0,
  sku text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_variants_pkey PRIMARY KEY (id),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.booking_intents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  artist_id uuid NOT NULL,
  service_id uuid NOT NULL,
  booking_date date NOT NULL,
  booking_time time without time zone NOT NULL,
  total_amount integer NOT NULL,
  meeting_address text,
  notes text,
  client_poc_name text,
  client_poc_phone text,
  artist_poc_name text,
  artist_poc_phone text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'cancelled'::text, 'failed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '02:00:00'::interval),
  CONSTRAINT booking_intents_pkey PRIMARY KEY (id),
  CONSTRAINT booking_intents_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.profiles(id),
  CONSTRAINT booking_intents_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(id),
  CONSTRAINT booking_intents_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.email_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  to_address text NOT NULL,
  subject text NOT NULL,
  template text NOT NULL,
  reference_id text,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text])),
  error_msg text,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_wishlists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT product_wishlists_pkey PRIMARY KEY (id),
  CONSTRAINT product_wishlists_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT product_wishlists_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.listing_packages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  partner_id uuid NOT NULL,
  package text NOT NULL CHECK (package = ANY (ARRAY['starter'::text, 'growth'::text, 'business'::text, 'premium'::text])),
  weeks integer NOT NULL,
  slots_total integer NOT NULL CHECK (slots_total > 0),
  slots_used integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'active'::text, 'cancelled'::text])),
  payfast_payment_id text,
  purchased_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT listing_packages_pkey PRIMARY KEY (id),
  CONSTRAINT listing_packages_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.profiles(id)
);